import { assetUrl } from "../../core/AssetUrls";

export const warshipIcon = assetUrl("sprites/warship.png");
export const cityIcon = assetUrl("images/flower-power/city.png");
export const factoryIcon = assetUrl("images/flower-power/factory.png");
export const goldCoinIcon = assetUrl("images/GoldCoinIcon.svg");
export const mirvIcon = assetUrl("sprites/mirv2.png");
export const missileSiloIcon = assetUrl("images/flower-power/missileSilo.png");
export const hydrogenBombIcon = assetUrl("sprites/hydrogenbomb.png");
export const atomBombIcon = assetUrl("sprites/atombomb.png");
export const portIcon = assetUrl("images/flower-power/port.png");
export const samLauncherIcon = assetUrl("images/flower-power/samLauncher.png");
export const defensePostIcon = assetUrl("images/flower-power/defensePost.png");
export const soldierIcon = assetUrl("images/SoldierIcon.svg");
export const claimIcon = assetUrl("images/ClaimIcon.svg");
export const profileIcon = assetUrl("images/ProfileIcon.svg");
export const guildIcon = assetUrl("images/GuildIconWhite.svg");
export const teamIcon = assetUrl("images/TeamIconSolidWhite.svg");
export const upperLimitIcon = assetUrl("images/UpperLimitIcon.svg");
export const allianceIcon = assetUrl("images/AllianceIcon.svg");
export const traitorIcon = assetUrl("images/TraitorIcon.svg");
